<?php  //[STAMP] 53c57fc00285732e5b04e7a4dfb07661
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait AcceptanceTester - \Helper\AcceptanceActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
